accounts/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('',views.LoginView.as_view(),name='login'),
    path('register/',views.RegisterView.as_view(),name='register'),
	# path('create/',views.create_post,name='create_post')
]

feed/urls.py
from django.urls import path
from . import views

app_name = 'feeds'

urlpatterns = [
    path('',views.FeedsView.as_view(),name='feeds'),
    path('comment/<int:feed_id>/',views.FeedsView.as_view(),name='comment'),
    path('like/<int:feed_id>/',views.LikeView.as_view(),name='like'),
    path('create_post/',views.CreatePost.as_view(),name='create_post'),
    path('search/',views.Search.as_view(),name='search'),
    path('archive/<int:feed_id>/',views.ArchivePost.as_view(),name='archive'),
    path('edit_post/<int:feed_id>/<int:image_id>/',views.EditPost.as_view(),name='edit_post'),
    path('edit_comment/<int:comment_id>/',views.EditComment.as_view(),name='edit_comment'),
    path('get_comment/<int:comment_id>/',views.EditComment.as_view(),name='get_comment'),
    path('delete_comment/<int:comment_id>/',views.DeleteComment.as_view(),name='delete_comment'),
    path('view_post/<int:pk>/',views.ViewPost.as_view(),name='view_post'),

]

instax/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('feeds/',include('feed.urls')),
    path('user_profile/',include('user_profile.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instax_v2/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('feeds/',include('feed.urls')),
    path('profile/',include('user_profile.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Account(models.Model):
	"""
	Accounts model
	
	"""
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	followers = models.IntegerField(default=0)
	following = models.IntegerField(default=0)
	prof_pic = models.ImageField(upload_to='prof_pic',blank=True,null=True)


class Followers(models.Model):
	"""
	Followers
	
	"""

	# followed_user = models.ManyToManyField(User)
	# follower_username = models.ForeignKey(User, related_name='user', on_delete=models.CASCADE)
	followed_user = models.ForeignKey(User,on_delete=models.CASCADE)
	follower_username = models.CharField(max_length=100)
	follow = models.BooleanField(default=False)

accounts/forms.py
from django import forms
from django.core.validators import RegexValidator
from django.core import validators
from django.contrib.auth.models import User
from django.shortcuts import render
from django.contrib.auth import authenticate


class RegisterValidation(forms.ModelForm):
	"""
	Register Validation
	"""

	first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder':('Enter your First Name')}),max_length=255)
	last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder':('Enter your Last Name')}),max_length=255)
	username = forms.CharField(widget=forms.TextInput(attrs={'placeholder':('Enter your Username')}),max_length=255)
	email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder':('Enter your Email Address')}),required=True)
	password = forms.CharField(widget = forms.TextInput(attrs={'placeholder':('Enter your Password'),'type':'password'}),max_length = 50,min_length=2)
	confirm = forms.CharField(widget = forms.TextInput(attrs={'placeholder':('Confirm Password'),'type':'password'}),max_length = 50,min_length=2)
	# account_model = Account.objects.all()
	

	class Meta:
		model = User
		fields = ('first_name','last_name','username','email','password')

	def clean_email(self):
		email = User.objects.filter(email=self.cleaned_data['email'])
		if email.exists():
			raise forms.ValidationError('Email already existed!')
		return self.cleaned_data['email']

	def clean_username(self):
		username = User.objects.filter(username=self.cleaned_data['username'])
		if username.exists():
			raise forms.ValidationError('Username already existed!')
		return self.cleaned_data['username']

	def clean(self):
		password = self.cleaned_data.get('password')
		confirm = self.cleaned_data.get('confirm')

		if password != confirm:
			raise forms.ValidationError('Passwords did not match!')
		return self.cleaned_data

class LoginValidation(forms.Form):
	"""
	Login Validation
	
	"""

	username = forms.CharField(widget=forms.TextInput(attrs={'placeholder':('Enter your Username')}),max_length = 255)
	password = forms.CharField(widget = forms.TextInput(attrs={'placeholder':('Enter your Password'),'type':'password'}),max_length = 50,min_length=2)
	# account_model = Account.objects.all()

	class Meta:
		model = User
		fields = ('username','password',)


	def clean(self):
		username = self.cleaned_data['username']
		password = self.cleaned_data['password']

		user = authenticate(username=username,password=password)

		if user is not None:
			return self.cleaned_data
		raise forms.ValidationError('Invalid Username or Password')

accounts/views.py
from django.shortcuts import render
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User
from .forms import RegisterValidation,LoginValidation
from .models import Account,Followers
from feed.models import Feeds,Comments,LikesUser
from django.views.generic import TemplateView
from feed.forms import CommentForm,FeedForm
from user_profile.forms import PicturesForm
from feed.forms import SearchForm

# Create your views here.
class RegisterView(TemplateView):
	"""
	Register View
	GET - get forms and render template
	POST - register user account, get user information
	"""

	template_name = 'accounts/register/register.html'
	context = User.objects.all()
	
	get_forms = RegisterValidation()
	comment_form = CommentForm()
	feed_form = FeedForm()
	picture_form = PicturesForm()
	search_form = SearchForm()
	
	def get(self, *args, **kwargs):
			
		return render(
			self.request,
			self.template_name, 
			{
				'context_data': self.context,
				'forms':self.get_forms
			}
		)

	def post(self,request, *args, **kwargs):
		
		form = RegisterValidation(request.POST)
		
		if form.is_valid():
			user = form.save()
			user.set_password(form.cleaned_data.get('password'))
			user.save()
			account = Account(user_id=user.id)
			account.save()

			user = authenticate(
					username=form.cleaned_data.get('username'),
					password=form.cleaned_data.get('password')
			)

			login(request,user)
			
			followers = Followers.objects.filter(follow=True,follower_username=request.user.username).values('followed_user_id')
		
			feed_data = Feeds.objects.filter(user_id__in=followers) | Feeds.objects.filter(user_id=request.user.id,archived=False)
			
			comment_data = Comments.objects.filter(post_id__in=feed_data.values('id'))
			
			feed_data._result_cache = None
		
			comment_data._result_cache = None


			package = {
				'feed_data':feed_data.order_by('-id'),
				'comment_data':comment_data,
				'user_data':request.user,
				'comment_form':self.comment_form,
				'feed_form':self.feed_form,
				'picture_form':self.picture_form,
				'search_form':self.search_form,
				'current_user':self.request.user
			}

		
			return render(request,'feed/users_page.html',package)

		return render(request,self.template_name,{'forms':form}) 


class LoginView(TemplateView):
	"""
	Login View

	"""

	template_name = 'accounts/login/login.html'
	get_forms = LoginValidation()
	comment_form = CommentForm()
	feed_form = FeedForm()
	picture_form = PicturesForm()	
	search_form = SearchForm()
	
	def get(self,*args,**kwargs):
	
		return render(self.request, self.template_name,{'forms':self.get_forms})

	
	def post(self,request, *args, **kwargs):
		
		forms = LoginValidation(self.request.POST)
		
		if forms.is_valid():
			user = authenticate(username=forms.cleaned_data.get('username'),password=forms.cleaned_data.get('password'))
			login(request,user)
			
			followers = Followers.objects.filter(follow=True,follower_username=request.user.username).values('followed_user_id')
		
			feed_data = Feeds.objects.filter(user_id__in=followers) | Feeds.objects.filter(user_id=request.user.id,archived=False)
			
			comment_data = Comments.objects.filter(post_id__in=feed_data.values('id'))
	
			package = {
				'feed_data':feed_data,
				'comment_data':comment_data,
				'forms':forms,
				'user_data': request.user,
				'comment_form':self.comment_form,
				'feed_form':self.feed_form,
				'picture_form':self.picture_form,
				'search_form':self.search_form,
				'current_user':request.user
			}

			return render(
				request,
				'feed/users_page.html',
				package
			)
		
		return render(
			request, 
			self.template_name,
			{'forms':forms }
		)

templates/accounts/register/register.html
{% extends 'accounts/base_create.html' %}
{% load static %}
{% load widget_tweaks %}

{% block register_title %}
<title>Register - Instax</title>
{% endblock register_title %}
	
				
{% block register %}

<h5>Sign up once and express yourself with Instax!</h5>
<form method="post">	
	{% csrf_token %}
	<div class="form-group">
		<label for="email" class="cols-sm-2 control-label">First Name</label>
		<div class="cols-sm-10">
			<div class="input-group">
				<span class="input-group-addon"><i class="fa fa-envelope fa" aria-hidden="true"></i></span>
				<!-- <input type="text" class="form-control" name="fname" id="fname"  placeholder="Enter your First Name"/> -->
				{{ forms.first_name|add_class:"form-control" }}
			</div>
		</div>
	</div>
	<div class="form-group">
		<label for="email" class="cols-sm-2 control-label">Last Name</label>
		<div class="cols-sm-10">
			<div class="input-group">
				<span class="input-group-addon"><i class="fa fa-envelope fa" aria-hidden="true"></i></span>
				<!-- <input type="text" class="form-control" name="lname" id="lname"  placeholder="Enter your Last Name"/> -->
				{{ forms.last_name|add_class:"form-control" }}
			</div>
		</div>
	</div>
	<div class="form-group">
		<label for="email" class="cols-sm-2 control-label">Your Email</label>
		<div class="cols-sm-10">
			<div class="input-group">
				<span class="input-group-addon"><i class="fa fa-envelope fa" aria-hidden="true"></i></span>
				<!-- <input type="text" class="form-control" name="email" id="email"  placeholder="Enter your Email"/> -->
				{{ forms.email|add_class:"form-control" }}
				
			</div>
		</div>
	</div>

	<div class="form-group">
		<label for="username" class="cols-sm-2 control-label">Username</label>
		<div class="cols-sm-10">
			<div class="input-group">
				<span class="input-group-addon"><i class="fa fa-users fa" aria-hidden="true"></i></span>
				<!-- <input type="text" class="form-control" name="username" id="username"  placeholder="Enter your Username"/> -->
				{{ forms.username|add_class:"form-control"}}
				
			</div>
		</div>
	</div>
	
	<div class="form-group">
		<label for="password" class="cols-sm-2 control-label">Password</label>
		<div class="cols-sm-10">
			<div class="input-group">
				<span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
				<!-- <input type="password" class="form-control" name="password" id="password"  placeholder="Enter your Password"/> -->
				{{ forms.password|add_class:"form-control"}}
				
			</div>
		</div>
	</div>

	<div class="form-group">
		<label for="confirm" class="cols-sm-2 control-label">Confirm Password</label>
		<div class="cols-sm-10">
			<div class="input-group">
				<span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
				<!-- <input type="password" class="form-control" name="confirm" id="confirm"  placeholder="Confirm your Password"/> -->
				{{ forms.confirm|add_class:"form-control"}}
			
			</div>
		</div>
	</div>
	
	{{ forms.username.errors }}
	{{ forms.non_field_errors }}
	{{ forms.email.errors }}
	
	<input type="submit" n class="btn btn-primary btn-lg btn-block register-button" value="Register" id="register"> 
	
</form>	
<a href="{% url 'account:login' %}" type="button" id="login" class="btn btn-primary btn-lg btn-block login-button">Login</a>
		
{% endblock register %}					
					