feed/urls.py
from django.urls import path
from . import views

app_name = 'feeds'

urlpatterns = [
    path('',views.FeedsView.as_view(),name='feeds'),
    path('comment/<int:feed_id>/',views.FeedsView.as_view(),name='comment'),
    path('like/<int:feed_id>/',views.LikeView.as_view(),name='like'),
    path('create_post/',views.CreatePost.as_view(),name='create_post'),
    path('search/',views.Search.as_view(),name='search'),
    path('archive/<int:feed_id>/',views.ArchivePost.as_view(),name='archive'),
    path('edit_post/<int:feed_id>/<int:image_id>/',views.EditPost.as_view(),name='edit_post'),
    path('edit_comment/<int:comment_id>/',views.EditComment.as_view(),name='edit_comment'),
    path('get_comment/<int:comment_id>/',views.EditComment.as_view(),name='get_comment'),
    path('delete_comment/<int:comment_id>/',views.DeleteComment.as_view(),name='delete_comment'),
    path('view_post/<int:pk>/',views.ViewPost.as_view(),name='view_post'),

]

instax/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('feeds/',include('feed.urls')),
    path('user_profile/',include('user_profile.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instax_v2/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('feeds/',include('feed.urls')),
    path('profile/',include('user_profile.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_profile/urls.py
from django.urls import path
from . import views

app_name = 'profile'

urlpatterns = [
	path('<str:username>',views.ProfileView.as_view(),name="profile"),
	path('follow/<str:username>',views.ProfileView.as_view(),name="follow"),
	path('edit_profile/',views.EditProfile.as_view(),name="edit"),
	path('change_password/',views.ChangePassword.as_view(),name="change_password"),
	path('delete_post/<int:feed_id>/',views.DeletePost.as_view(),name='delete_post'),	
	path('unarchive_post/<int:feed_id>/',views.UnarchivePost.as_view(),name='unarchive'),
	path('logout/',views.Logout.as_view(),name='logout'),
	path('user/<str:username>',views.UserProfileView.as_view(),name='profile_user')
]

user_profile/models.py
from django.db import models


from django.contrib.auth.models import User

# Create your models here.
class PicturesUser(models.Model):
	"""
	Pictures of the user 
	"""

	user = models.ForeignKey(User,on_delete=models.CASCADE)
	image = models.ImageField(upload_to='insta_pics')

user_profile/forms.py
from django import forms
from user_profile.models import PicturesUser
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from accounts.models import Account


class PicturesForm(forms.ModelForm):
	"""
	Picture Form, add picture to gallery or use picture as post

	"""
	image = forms.ImageField()

	class Meta:
		model = PicturesUser
		fields = ('image',)


class EditProfileForm(UserChangeForm):
	"""
	Edit Profile Form

	Update profile information
	"""
	
	first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder':('Enter your First Name')}),max_length=255,label='First Name')
	last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder':('Enter your Last Name')}),max_length=255)
	username = forms.CharField(widget=forms.TextInput(attrs={'placeholder':('Enter your Username')}),max_length=255)
	email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder':('Enter your Email Address')}),required=True)
	
	class Meta:
		model = User
		fields = ('first_name','last_name','username','email')


class ProfPicForm(forms.ModelForm):
	"""
	Prof Pic Form
	Set/change profile picture
	
	"""
	class Meta:
		model = Account
		fields = ('prof_pic',)

user_profile/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView,View
from django.core import serializers
from django.http import JsonResponse
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.urls import reverse
from accounts.models import Account,Followers
from user_profile.models import PicturesUser
from feed.models import Feeds
from accounts.serializers import FollowerSerializer
from feed.serializers import FeedSerialize
from .serializers import UserSerialize,ProfPicSerialize
from feed.forms import SearchForm
from .forms import EditProfileForm,ProfPicForm
from django.contrib.auth import logout
from accounts.views import LoginView


class ProfileView(TemplateView):
	"""
	Profile View
	GET - get number of followers,profile pic, search form etch.
	POST - follow/unfollow user

	"""
	
	template_name = 'user_profile/profile.html'

	followers = Followers.objects.all()
	
	def get(self,request,*args,**kwargs):
		username = kwargs.get('username')

		current_user = self.request.user
		
		account = User.objects.get(username=username)
		
		pictures = PicturesUser.objects.filter(user_id=account.id)
		
		search_form = SearchForm()

		try:
			followed = Followers.objects.values(
				'followed_user__username',
				'follower_username',
				'follow'
		
			).get(
		
				followed_user__username=account.username,
				follower_username=self.request.user.username
			)
		
		except:
		
			followed = False

		try: 	
			package = {
				'user_data':account,
				'followers':self.followers,
				'no_prof_pic':False,
				'pictures':pictures,
				'search_form':search_form,
				'current_user':current_user,
				'followed': followed,
			}
			
			return render(
				request,
				self.template_name,
				package
			)

		except:
			package = {
				'user_data': account,
				'followers':self.followers,
				'no_prof_pic':True,
				'pictures':pictures,
				'search_form':search_form,
				'current_user': current_user,
				'followed':followed,
			}
			
			return render(
				request,
				self.template_name,
				package
			)


	def post(self,request,*args,**kwargs):
		user = User.objects.get(username=kwargs.get('username'))
		following_user = Account.objects.get(user_id=request.user.id)
		follow_account = Account.objects.get(user_id=user.id)
		
		try:
			account_follow =  Followers.objects.values(
				'followed_user__username',
				'follower_username',
				'follow'
			).get(
				followed_user__username=user.username,
				follower_username=self.request.user.username
			)

			if account_follow.get('follow') == True:
				follow_account.followers-=1
				following_user.following-=1

				unfollow = Followers.objects.get(followed_user_id=user.id)
				unfollow.follow = False

				unfollow.save()
				follow_account.save()
				following_user.save()
				
				data = {
					'follow':unfollow.follow,
					'followers': follow_account.followers
					}
				
				return JsonResponse(data, safe=False)

			else:
				follow_account.followers+=1
				following_user.following+=1

				follow = Followers.objects.get(followed_user_id=user.id)
				follow.follow = True
				follow_account.save()
				follow.save()
				following_user.save()
				
				data = {
					'follow':follow.follow,
					'followers': follow_account.followers
					}
				
				return JsonResponse(data, safe=False)
			
		except:
			follow_account.followers+=1
			following_user.following+=1

			follow = Followers(
				followed_user_id=user.id,
				follower_username=self.request.user,
				follow=True
			)

			follow.save()
			follow_account.save()
			following_user.save()
			
			data = {
					'follow':follow.follow,
					'followers': follow_account.followers
					}
				
			return JsonResponse(data, safe=False)


class UserProfileView(TemplateView):
	"""
	View User Profile
	"""

	template_name = 'user_profile/profile.html'

	followers = Followers.objects.all()
	
	def get(self,request,*args,**kwargs):

		current_user = self.request.user
		
		account = User.objects.get(username=request.user.username)
		
		pictures = PicturesUser.objects.filter(user_id=account.id)
		
		search_form = SearchForm()

		try:
			followed = Followers.objects.values(
				'followed_user__username',
				'follower_username',
				'follow'
		
			).get(
		
				followed_user__username=account.username,
				follower_username=self.request.user.username
			)
		
		except:
			followed = False

		
		try: 	
			package = {
				'user_data':account,
				'followers':self.followers,
				'no_prof_pic':False,
				'pictures':pictures,
				'search_form':search_form,
				'current_user':current_user,
				'followed': followed,
			}
			
			return render(
				request,
				self.template_name,
				package
			)

		except:
			package = {
				'user_data': account,
				'followers':self.followers,
				'no_prof_pic':True,
				'pictures':pictures,
				'search_form':search_form,
				'current_user': current_user,
				'followed':followed,
			}
			
			return render(
				request,
				self.template_name,
				package
			)


class EditProfile(TemplateView):
	"""
	Edit profile

	"""
	template_name = "user_profile/edit_profile.html"
	
	def get(self,request,*args,**kwargs):
		search_form = SearchForm()
		edit_form = EditProfileForm(instance=request.user)
		change_password_form = PasswordChangeForm(user=request.user)
		account = Account.objects.get(user_id=request.user.id)
		archived_post = Feeds.objects.filter(user_id=self.request.user.id,archived=True)
		prof_pic_form = ProfPicForm()

		try:
			account.prof_pic.url
			prof_pic = account.prof_pic.url
		except:
			prof_pic = False

		package = {
			'account_user':account,
			'current_user':request.user,
			'search_form':search_form,
			'edit_form': edit_form,
			'prof_pic_form':prof_pic_form,
			'archived_post':archived_post,	
			'change_password_form':change_password_form,
			'prof_pic':prof_pic,
		}
		
		return render(request,self.template_name,package)

	def post(self,request,*args,**kwargs):
		user = User.objects.get(username=request.user.username)
		account_user = Account.objects.get(user_id=request.user.id)
		search_form = SearchForm()
		edit = EditProfileForm(request.POST,instance=request.user)
		prof_pic_form = ProfPicForm(data=request.POST,files=request.FILES,instance=account_user)
		
		try:
			account.prof_pic.url
			prof_pic = account.prof_pic.url
		except:
			prof_pic = False

		if edit.is_valid() and prof_pic_form.is_valid():
			edit.save()
			prof_pic_form.save()
			serialize_edit = UserSerialize(User.objects.get(username=request.user.username))
			serialize_pic = ProfPicSerialize(Account.objects.get(user_id=request.user.id))
			data = {
				'profile': serialize_edit.data,
				'prof_account': serialize_pic.data
			}

			return JsonResponse(data, safe=False)

		else:
			return JsonResponse({'errors':edit.errors},safe=False)


class ChangePassword(View):
	"""
	Change Password

	"""
	template_name = "user_profile/edit_profile.html"
	
	def post(self,request,*args,**kwargs):
		search_form = SearchForm()
		edit_form = EditProfileForm(instance=request.user)
		change_password_form = PasswordChangeForm(user=request.user)
		account = Account.objects.get(user_id=request.user.id)
		prof_pic_form = ProfPicForm()
		
		password_form = PasswordChangeForm(data=request.POST,user=request.user)

		try:
			account.prof_pic.url
			prof_pic = account.prof_pic.url
		except:
			prof_pic = False

		package = {
			'account_user':account,
			'current_user':request.user,
			'search_form':search_form,
			'edit_form': edit_form,
			'change_password_form': password_form,
			'prof_pic_form':prof_pic_form,
			'prof_pic':prof_pic,
		}

		if password_form.is_valid():
			password_form.save()
			update_session_auth_hash(request,password_form.user)
			print('if')
			package['success'] = "New Password Set"
			return render(request,self.template_name,package)


		else:
			print('else')
			package['errors'] = password_form.errors
			package['pic_errors'] = prof_pic_form.errors
			return render(request,self.template_name,package)


class DeletePost(View):
	"""
	Delete Post
	POST - delete post completely from archive
	
	"""

	def post(self,request,*args,**kwargs):
		feed = Feeds.objects.get(id=kwargs.get('feed_id'))
		feed_serialize = FeedSerialize(feed)
		serialized = feed_serialize.data
		PicturesUser.objects.get(id=feed.images.id).delete()
		return JsonResponse({'data': serialized},safe=False)


class UnarchivePost(View):
	"""
	Unarchive Post
	POST - remove post from archive, restore it to feeds
	"""

	def post(self,request,*args,**kwargs):
		feed = Feeds.objects.get(id=kwargs.get('feed_id'))
		feed.archived= False;
		feed.save()
		feed_serialize = FeedSerialize(feed)
		serialized = feed_serialize.data
		return JsonResponse({'data':serialized},safe=False)


class Logout(TemplateView):
	"""
	Logout the user
	GET - log out current user, redirect to login page
	"""
	
	template_name = 'accounts/login/login.html'

	def get(self,request,*args,**kwargs):
		logout(request)
		return HttpResponseRedirect(reverse('account:login'))










		




		

templates/user_profile/edit_profile.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
<title>Edit Profile</title>
{% endblock title %}

{% block search %}
	<form method='get' action="{% url 'feeds:search' %}" class="search">
		{% csrf_token %}
		{{ search_form.search }}
	</form>
{% endblock search %}

{% block feed_url %}
<a href="{% url 'feeds:feeds'%}"><h1 class="title" style="margin-top: -5px; margin-right: -30px">𝐼𝓃𝓈𝓉𝒶𝓍</h1></a>
{% endblock feed_url %}

{% block profile_url %}
<a href="{% url 'profile:profile' current_user.username %}"><img src='http://freeiconbox.com/icon/256/23228.png' class='nav-icon'></a>
{% endblock profile_url %}

{% block content %}
<div class="main-body">

	<div class="tab">
		<button class="tablinks" onclick="change_edit(event, 'Edit')" id="defaultOpen">Edit Profile</button>
		<button class="tablinks" onclick="change_edit(event, 'Change')">Change Password</button>
		<button class="tablinks" onclick="change_edit(event, 'Feed Archive')">Feed Archive</button>
		<button class="tablinks" onclick="change_edit(event, 'Logout')">Log out</button>

	</div>
	
	<div id="Edit" class="tabcontent">
		{% if prof_pic != False %}
		<img src="{{ account_user.prof_pic.url }}" style="border-radius: 50%; margin-top: 40px; width: 150px;" id='display_pic'>
		{% else %}
		<img src="{% static 'user_profile/img/blank_picture.png' %}" style="border-radius: 50%; margin-top: 40px; width: 150px;" id='display_pic'>
		{% endif %}
		<br><br>
		<form action="{% url 'profile:edit' %}" method="post" class="edit_profile" enctype="multipart/form-data">
		{% csrf_token %}
			<h4 class="post">Profile Picture</h4>	
			{% render_field prof_pic_form.prof_pic class="form-control" %}
			<br>
			<h4 class="post">First Name</h4> 
			{% render_field edit_form.first_name class="form-control" %}
			<br>
			<h4 class="post">Last Name</h4> 
			{% render_field edit_form.last_name class="form-control"  %}
			<br>
			<h4 class="post">Username</h4> 
			{% render_field edit_form.username class="form-control"  %}
			<br>
			<h4 class="post">Email Address</h4> 
			{% render_field edit_form.email class="form-control"  %}
			<br><br><br>
			
			<div id="edit_prof_notif"></div>
			<div id='errors'></div>

			<button id='edit-btn' class="btn btn-primary btn-lg btn-block register-button" type="submit" style="width: 100px;margin-left: 362px;">
				Submit
			</button>
		</form>
	</div>

	<div id="Change" class="tabcontent">
		<br><br>
		<form action="{% url 'profile:change_password' %}" method="post" class="change_pass">
			<h4 class="post">Old Password</h4>
			{% csrf_token %}
				{% render_field change_password_form.old_password class="form-control" %}
				<br>
				<h4 class="post">New Password</h4>
				{% render_field change_password_form.new_password1 class="form-control" %}
				<br>
				<h4 class="post">Confirm Password</h4>
				{% render_field change_password_form.new_password2 class="form-control" %}
				<br>
				{% for error in errors.old_password %}
					<h4>{{ error }}</h4>
				{% endfor %}
				{% for error in errors.new_password2 %}
					<h4>{{ error }}</h4>
				{% endfor %}

				<h4> {{ success }} </h4>
				<button id='change-pass-btn' class="btn btn-primary btn-lg btn-block register-button" type="submit" style="width: 100px;margin-left: 362px;">
					Submit
				</button>
		</form>
	</div>
	
	<div id="Feed Archive" class="tabcontent" style="overflow-y: scroll;">
		<br><br>
		{% for archive in archived_post %}
			<div id="archive-id-{{ archive.id }}" class="archive-left" style="padding-bottom: 300px;border-bottom: 1px solid #C6BEB0;border-right: 1px solid #C6BEB0;border-left: 1px solid #C6BEB0;border-top: 1px solid #C6BEB0;">
				<form action="{% url 'profile:delete_post' archive.id %}" method="post" class="delete_archive">
					{% csrf_token %}
					<p align="right" style="float:right;"><button type="submit">✖</button></p>
					
				</form>
				
				<form action="{% url 'profile:unarchive' archive.id %}" method="post" class="restore_post">
					{% csrf_token %}
					<p align="right" style="float:right;"><button type="submit">🔙</button></p>
				</form>
				<span>
					<p align="left" style="font-family: 'Passion One', cursive;float:left;">{{ archive.user.username }}| </p>
					<p align="justify"> &nbsp {{ archive.caption }}</p>
					
				</span>
				<img src=" {{ archive.images.image.url }}" width="449px" height="240px" align="left">
				<br><br>
			</div>
			
		{% endfor %}
		
	</div>

	<div id="Logout" class="tabcontent">
		{% if prof_pic != False %}
		<img src="{{ account_user.prof_pic.url }}" style="border-radius: 50%; margin-top: 40px; width: 150px;" id='display_pic'>
		{% else %}
		<img src="{% static 'user_profile/img/blank_picture.png' %}" style="border-radius: 50%; margin-top: 40px; width: 150px;" id='display_pic'>
		{% endif %}
		<br><br>
		<h4 class="post">Are you sure you want to log out?</h4>
		<form action="{% url 'profile:logout' %}" method="get">
			<button id='logout' class="btn btn-primary btn-lg btn-block register-button" type="submit" style="width: 100px;margin-left: 180px;">
				Logout
			</button>
		</form>
	</div>
</div>

{% endblock content %}

{% block tabscript %}
<script>
function change_edit(event, option) {
	var i, tabcontent, tablinks;

	tabcontent = document.getElementsByClassName("tabcontent");
	for (i = 0; i < tabcontent.length; i++) {
		tabcontent[i].style.display = "none";
	}

	tablinks = document.getElementsByClassName("tablinks");
		for (i = 0; i < tablinks.length; i++) {
	tablinks[i].className = tablinks[i].className.replace(" active", "");
	}

	document.getElementById(option).style.display = "block";
  	event.currentTarget.className += " active";
}

document.getElementById("defaultOpen").click();
event.currentTarget.className += " active";
</script>
{% endblock tabscript %}

templates/user_profile/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Profile</title>
{% endblock title %}

{% block search %}
	<form method='get' action="{% url 'feeds:search' %}" class="search">
		{% csrf_token %}
		{{ search_form.search }}
	</form>
{% endblock search %}

{% block feed_url %}
<a href="{% url 'feeds:feeds'%}"><h1 class="title" style="margin-top: -5px; margin-right: -30px">𝐼𝓃𝓈𝓉𝒶𝓍</h1></a>
{% endblock feed_url %}

{% block profile_url %}
<a href="{% url 'profile:profile' current_user.username %}"><img src='http://freeiconbox.com/icon/256/23228.png' class='nav-icon'></a>
{% endblock profile_url %}

{% block content %}
	<div class="main-body">
		{% if no_prof_pic == True %}
		<div id="left">
			<img src="{% static 'user_profile/img/blank_picture.png' %}" style="border-radius: 50%; margin-top: 40px; width: 150px;">
		</div>
		
		{% else %}
		<div id="left">
			<img src="{{ user_data.account.prof_pic.url }}" style="border-radius: 50%; margin-top: 40px; ">
		</div>

		{% endif %}
		
		<div id="center">
			<div class="padding" style="margin-left: 200px; margin-top: : 20px;">
				<h4 class="post" style="margin-bottom: : 20px;text-align: left;font-size: 40px;"> {{ user_data.username }} </h4>
				<div id='no-followers' class="post" style="text-align: left;font-size: 20px;display: inline; float: left;">  Followers {{ user_data.account.followers }} &nbsp&nbsp&nbsp&nbsp&nbsp</div>
				<div class="post" style="text-align: left;font-size: 20px;display:inline;float: left;"> Following {{ user_data.account.following }} </div><br><br>
				<h4 class="post" style="text-align: left;font-size: 25px"> {{ user_data.first_name }} {{ user_data.last_name}}</h4>
				
			</div>
		</div>
		<br><br>
		{% if current_user.username != user_data.username %}
		<div id="left">
			<form action="{% url 'profile:follow' user_data.username %}" method='post' class="follow">
			{% csrf_token %}
				{% if followed.follow == True %}
				<button id='follow-btn' class="btn btn-primary btn-lg btn-block register-button" type="submit" style="width: 100px;margin-left: 45px;">
					Following
				</button>
				{% else %}
				<button id='follow-btn' class="btn btn-primary btn-lg btn-block register-button" type="submit" style="width: 100px;margin-left: 45px;">
					Follow
				</button>
				{% endif %}
				
			</form>
		</div>
		{% else %}
		<div id="left">
			<a href="{% url 'profile:edit' %}" class="btn btn-primary btn-lg btn-block register-button"  style="width: 180px;margin-left: 15px;margin-top: 45px;">
				Account Settings
			</a>

		</div>
		{% endif %}
		<br><br><br><br><br>	
	</div>
		<div class="padding-gallery">
			<span>
				{% for images in pictures %}
				<a href="#"><img src="{{ images.image.url }}" width="300px" height="200px" align="left" style="padding: 15px 15px 15px 15px"></a> 
				{% endfor %}
			</span>
		</div>
		
{% endblock content %}