feed/urls.py
from django.urls import path
from . import views

app_name = 'feeds'

urlpatterns = [
    path('',views.FeedsView.as_view(),name='feeds'),
    path('comment/<int:feed_id>/',views.FeedsView.as_view(),name='comment'),
    path('like/<int:feed_id>/',views.LikeView.as_view(),name='like'),
    path('create_post/',views.CreatePost.as_view(),name='create_post'),
    path('search/',views.Search.as_view(),name='search'),
    path('archive/<int:feed_id>/',views.ArchivePost.as_view(),name='archive'),
    path('edit_post/<int:feed_id>/<int:image_id>/',views.EditPost.as_view(),name='edit_post'),
    path('edit_comment/<int:comment_id>/',views.EditComment.as_view(),name='edit_comment'),
    path('get_comment/<int:comment_id>/',views.EditComment.as_view(),name='get_comment'),
    path('delete_comment/<int:comment_id>/',views.DeleteComment.as_view(),name='delete_comment'),
    path('view_post/<int:pk>/',views.ViewPost.as_view(),name='view_post'),

]

instax/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('feeds/',include('feed.urls')),
    path('user_profile/',include('user_profile.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instax_v2/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('feeds/',include('feed.urls')),
    path('profile/',include('user_profile.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_profile/urls.py
from django.urls import path
from . import views

app_name = 'profile'

urlpatterns = [
	path('<str:username>',views.ProfileView.as_view(),name="profile"),
	path('follow/<str:username>',views.ProfileView.as_view(),name="follow"),
	path('edit_profile/',views.EditProfile.as_view(),name="edit"),
	path('change_password/',views.ChangePassword.as_view(),name="change_password"),
	path('delete_post/<int:feed_id>/',views.DeletePost.as_view(),name='delete_post'),	
	path('unarchive_post/<int:feed_id>/',views.UnarchivePost.as_view(),name='unarchive'),
	path('logout/',views.Logout.as_view(),name='logout'),
	path('user/<str:username>',views.UserProfileView.as_view(),name='profile_user')
]

feed/models.py
from django.db import models
from django.contrib.auth.models import User
from user_profile.models import PicturesUser
from accounts.models import Account


class Feeds(models.Model):
	"""
	Feed
	
	"""
	
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	images = models.ForeignKey(PicturesUser,on_delete=models.CASCADE,blank = True,null=True)
	likes = models.IntegerField(default=0)
	liker = models.ManyToManyField(Account,blank=True)
	liked = models.ManyToManyField('LikesUser',blank=True)
	caption = models.TextField(blank=True)
	archived = models.BooleanField(default=False)


class Comments(models.Model):
	"""
	Comment
	
	"""
	
	post = models.ForeignKey(Feeds,on_delete=models.CASCADE)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	comment = models.TextField()
	commented_at = models.DateTimeField(auto_now_add=True)
	archived_comment = models.BooleanField(default=False)


class LikesUser(models.Model):
	"""
	Likes
	
	"""
	
	feed = models.ForeignKey(Feeds, on_delete=models.CASCADE,null=True)
	user = models.ForeignKey(User,on_delete=models.CASCADE)
	liked = models.BooleanField(default=False)

feed/forms.py
from django import forms
from .models import Comments,LikesUser,Feeds
from user_profile.models import PicturesUser


class CommentForm(forms.ModelForm):
	"""
	Comment Form, comment on posts

	"""

	comment = forms.CharField(max_length=255, label='',widget=forms.Textarea(attrs={
		'id':'create-comment-field',
		'placeholder':('Place Comments Here'),
		'rows':5,
		'cols': 82,
		'style': "margin-left: 0px;border: 1px solid grey;border-radius: 10px;",
		}))


	class Meta:
		model = Comments
		fields = ('comment',)

	def clean(self):
		return self.cleaned_data


class FeedForm(forms.ModelForm):
	"""
	Post Form, create posts

	"""
	caption = forms.CharField(max_length=255, label='',widget=forms.Textarea(attrs={
		'id':'create-caption-field',
		'placeholder':('What is on your mind?'),
		'rows':5,
		'cols': 82,
		'style': "margin-left: 0px;border: 1px solid grey;border-radius: 10px;",
		}))

	class Meta:
		model = Feeds
		fields = ('caption',)

	def clean(self):
		return self.cleaned_data


class SearchForm(forms.Form):
	"""
	Search form, search for users
	"""
	search = forms.CharField(max_length=100, label='',required=False,widget=forms.TextInput(attrs={
		'id':'search-field',
		'type': 'text',
		'placeholder': 'Search',
		'style': 'text-align: center; width: 297px;margin-left:20px;',
		}))


		    	

feed/views.py
from __future__ import unicode_literals
from django.views.generic import TemplateView,View
from django.views.generic.detail import DetailView
from django.http import JsonResponse
from django.shortcuts import render
from django.core import serializers
from django.contrib.auth.models import User
from .models import Feeds,Comments,LikesUser
from accounts.models import Account,Followers
from user_profile.models import PicturesUser
from feed.forms import CommentForm,FeedForm,SearchForm
from user_profile.forms import PicturesForm
from .serializers import CommentSerialize,FeedSerialize,LikesSerialize


class FeedsView(TemplateView):
	"""
	Feeds View
	GET - render template, send context data
	POST - return json response to display recently added comments

	"""
	template_name = 'feed/users_page.html'
	comment_form = CommentForm()	
	feed_form = FeedForm()
	picture_form = PicturesForm()
	search_form = SearchForm()
	
	
	def get(self,request, *args, **kwargs):
		followers = Followers.objects.filter(follow=True,follower_username=request.user.username).values('followed_user_id')
		
		feed_data = Feeds.objects.filter(user_id__in=followers,archived=False) | Feeds.objects.filter(user_id=request.user.id,archived=False)
	
		comment_data = Comments.objects.filter(post_id__in=feed_data.values('id'))
			
		feed_data._result_cache = None
		
		comment_data._result_cache = None
		
		package = {
			'feed_data': feed_data.order_by('-id'),
			'comment_data':comment_data,
			'user_data':request.user,
			'comment_form':self.comment_form,
			'feed_form':self.feed_form,
			'picture_form':self.picture_form,
			'search_form':self.search_form,
			'current_user':self.request.user,
		}
		
		return render(
			request, 
			self.template_name,
			package
		)

	def post(self,request, *args, **kwargs):
		form = CommentForm(self.request.POST)	
		
		feed = Feeds.objects.get(id=kwargs.get('feed_id'))
		
		if form.is_valid():
			
			comment = form.save(commit=False)
			comment.post_id = feed.id
			comment.user_id = self.request.user.id
			comment.save()
			comment.refresh_from_db()
			
			serializer = CommentSerialize(Comments.objects.get(id=comment.id))
			serialized = serializer.data
			serialized['username'] = comment.user.username
			serialized['current_user'] = request.user.username
			
			return JsonResponse(serialized, safe=False)


class LikeView(View):
	"""
	Likes View 
	GET - retrieve username and prof pic, return json to display accounts that liked the post
	POST - each user can like a post once, if a post is already liked, then the user clicked the like button, it will be unliked

	"""

	def get(self,request,*args,**kwargs):

		feed_likers = Feeds.objects.get(
			id=kwargs.get('feed_id')).liker.all().values(
					'user__username',
					'prof_pic'
				)
		
		serializer = {
			'data': list(feed_likers)
		}
		
		return JsonResponse(serializer, safe=False)
		

	def post(self,request,*args,**kwargs):

		feed_data = Feeds.objects.get(id=kwargs.get('feed_id'))
		# like_user = LikesUser.objects.get(feed_id=kwargs.get('feed_id')).liked.filter(user_id=request.user.id)
		
		try:
			like_user = Feeds.objects.get(id=kwargs.get('feed_id')).liked.get(user_id=request.user.id)
			account_user = Account.objects.get(user_id=self.request.user.id)

			if like_user.liked == True:
				feed_data.likes-=1
				feed_data.liker.remove(account_user)
				like_user.liked = False
				like_user.save()
				feed_data.liked.add(like_user)
				feed_data.save()
				feed_serializer = FeedSerialize(feed_data)
				serialized = feed_serializer.data
				return JsonResponse(serialized, safe=False)
				
			else:
				feed_data.likes+=1
				feed_data.liker.add(account_user)
				like_user.liked = True
				like_user.save()
				feed_data.liked.add(like_user)
				feed_data.save()
				feed_serializer = FeedSerialize(feed_data)
				serialized = feed_serializer.data
				return JsonResponse(serialized, safe=False)
				
		except:
			account_user = Account.objects.get(user_id=self.request.user.id)
			like_user = LikesUser(feed_id=kwargs.get('feed_id'),user_id=self.request.user.id,liked=True)
			feed_data.likes+=1
			feed_data.liker.add(account_user)	
			like_user.save()
			feed_data.liked.add(like_user)
			feed_data.save()
			feed_serializer = FeedSerialize(feed_data)
			serialized = feed_serializer.data
			return JsonResponse(serialized, safe=False)


class CreatePost(View):
	"""
	Create Posts
	POST - return json response to display newly created posts

	"""

	def post(self, request,*args,**kwargs):
		caption = FeedForm(request.POST)
		image = PicturesForm(data=request.POST,files=request.FILES)

		if caption.is_valid() and image.is_valid():
			caption = caption.save(commit=False)
			image = image.save(commit=False)
			image.user_id = request.user.id
			image.save()
			caption.user_id = request.user.id
			caption.images_id = image.id
			caption.save()
			serialize = FeedSerialize(caption)
			new_post = serialize.data
			new_post['username'] = caption.user.username
			new_post['image'] = caption.images.image.url
			new_post['image_id'] = image.id
			try:
				new_post['prof_pic'] = caption.user.account.prof_pic.url
				return JsonResponse(new_post, safe=False)
			except:
				return JsonResponse(new_post, safe=False)


class Search(View):
	"""
	Search
	GET - search for users, return json response to acquire searched user

	"""

	def get(self,request,*args,**kwargs):
		search_form = SearchForm(self.request.GET)

		if search_form.is_valid():
			search_username = Account.objects.filter(user__username=search_form.cleaned_data['search']).values('user__username','prof_pic')
			serialize = {'data': list(search_username)}
			return JsonResponse(serialize,safe=False)


class ArchivePost(View):
	"""
	POST - archive post, not completely deleting the post, instead view archived posts in edit profile menu
	"""

	def post(self,request,*args,**kwargs):
		feed = Feeds.objects.get(id=kwargs.get('feed_id'))
		feed.archived = True
		feed.save()
		feed_serialize = FeedSerialize(feed)
		serialized = feed_serialize.data
		return JsonResponse(serialized,safe=False)


class EditPost(View):
	"""
	GET - get edit forms, to display in template view
	POST - save recently edited object, returns JSON response to display in template view
	"""
	def get(self,request,*args,**kwargs):
		feed = Feeds.objects.get(id=kwargs.get('feed_id'))
		image = PicturesUser.objects.get(id=kwargs.get('image_id'))
		feed_serialize = FeedSerialize(feed)
		serialized = feed_serialize.data
		serialized['image'] = image.image.url
		serialized['username'] = feed.user.username
		serialized['image_id'] = image.id
		return JsonResponse(serialized,safe=False)


	def post(self, request, *args, **kwargs):
		feed = Feeds.objects.get(id=kwargs.get('feed_id'))
		image = PicturesUser.objects.get(id=kwargs.get('image_id'))
		feed_form = FeedForm(request.POST,instance=feed)
		image_form = PicturesForm(data=request.POST,files=request.FILES,instance=image)
		
		if feed_form.is_valid() and image_form.is_valid():
			feed_form.save()
			image_form.save()

			serialize_feed = FeedSerialize(Feeds.objects.get(id=kwargs.get('feed_id'))).data
			image_new = PicturesUser.objects.get(id=kwargs.get('image_id'))
			serialize_feed['image'] = image_new.image.url
			serialize_feed['username'] = feed.user.username
			return JsonResponse(serialize_feed,safe=False)


class EditComment(View):
	"""
	Edit Comments
	"""
	def get(self,request,*args,**kwargs):
		comment = Comments.objects.get(id=kwargs.get('comment_id'))
		comment_serialize = CommentSerialize(comment).data

		return JsonResponse(comment_serialize,safe=False)


	def post(self,request,*args,**kwargs):
		comment = Comments.objects.get(id=kwargs.get('comment_id'))
		comment_form = CommentForm(request.POST,instance=comment)

		if comment_form.is_valid():
			comment_form.save()
			
			comment_serialize = CommentSerialize(Comments.objects.get(id=kwargs.get('comment_id'))).data

			comment_serialize['username'] = comment.user.username
			comment_serialize['current_user'] = request.user.username
			return JsonResponse(comment_serialize,safe=False)


class DeleteComment(View):
	"""
	Delete COmments

	"""

	def post(self,request,*args,**kwargs):
		comment = Comments.objects.get(id=kwargs.get('comment_id'))
		comment_serialize = CommentSerialize(comment).data
		comment_serialize['username'] = comment.user.username
		comment_serialize['current_user'] = request.user.username

		Comments.objects.get(id=kwargs.get('comment_id')).delete()

		return JsonResponse(comment_serialize,safe=False)


class ViewPost(DetailView):
	"""
	View Post
	"""

	model = Feeds
	template_name = "feed/feed_view.html"

	def get_context_data(self,**kwargs):
		context = super(ViewPost,self).get_context_data(**kwargs)
		context['comment_data'] = Comments.objects.filter(post_id=context.get('feeds').id)
		context['comment_form'] = CommentForm()
		context['search_form'] = SearchForm()
		context['user_data'] = self.request.user
		context['current_user'] = self.request.user
		context['feed_form'] = FeedForm()
		context['picture_form'] = PicturesForm()

		return context


		

templates/feed/feed_user.html
{%extends 'base.html'%}
{% load static %}

{% block title %}
<title>Profile	</title>
{% endblock title %}

{% block feed_url %}
<a href="#"><h1 class="title" style="margin-top: -5px; margin-right: -30px">𝐼𝓃𝓈𝓉𝒶𝓍</h1></a>
{% endblock feed_url %}

{% block profile_url %}
<a href="#"><img src='http://freeiconbox.com/icon/256/23228.png' class='nav-icon'></a>
{% endblock profile_url %}

{% block content %}
	<div class="main-body">
		{% if no_prof_pic == True %}
		<div id="left">
			<img src="{% static 'user_profile/img/blank_picture.png' %}" style="border-radius: 50%; margin-top: 40px; ">
		</div>
		
		{% else %}
		<div id="left">
			<img src="{{ profile.prof_pic.url }}" style="border-radius: 50%; margin-top: 40px; ">
		</div>
		{% endif %}
		
		<div id="center">
			<div class="padding" style="margin-left: 200px; margin-top: : 20px;">
				<h4 class="post" style="margin-bottom: : 20px;text-align: left;font-size: 40px;"> {{ profile.username }} </h4>
				<h4 class="post" style="text-align: left;font-size: 20px;"> {{ profile.followers }} Followers </h4><br>
				<h4 class="post" style="text-align: left;font-size: 25px"> {{ profile.first_name }} {{ profile.last_name}}</h4>

			</div>
		</div>
		
		<br><br><br><br><br><br>
	</div>
		<div class="padding-gallery">
			<span>
				{% for images in pictures %}
				<a href="#"><img src="{{ images.image.url }}" width="300px" height="200px" align="left" style="padding: 15px 15px 15px 15px"></a> 
				{% endfor %}
			</span>
		</div>
		
{% endblock content %}

templates/feed/users_page.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}


{% block title %}
<title>Feeds - {{ user_data.username }}</title>
{% endblock title %}

{% block feed_url %}
<a href="{% url 'feeds:feeds' %}">
	<h1 class="title" class="logo-position">𝐼𝓃𝓈𝓉𝒶𝓍</h1>
</a>
{% endblock feed_url %}


{{ user_data.username }}

{% block search %}
	<form method='get' action="{% url 'feeds:search' %}" class="search">
		{% csrf_token %}
		<!-- <input id="input-field" type="text" placeholder='Search' style="text-align: center"> -->
		{{ search_form.search }}
	</form>
{% endblock search %}

{% block content %}

<div class="main-body">
	<form action="{% url 'feeds:create_post' %}" method="post" enctype="multipart/form-data" class="create-post">
		{% csrf_token %}
		<div id="nav-container" class="nav-container-position">
			<div id="navbar">
				<div id="left" >
					<h4 class="post" style="text-align: left;margin-top: -10px;margin-left: 20px;">Create post</h4>
				</div>
				{{ feed_form.caption }}
				<div id="left" style="margin-left: 89px;">
					{{ picture_form.image}}
				</div>
				<div id="right">
					<button  class="btn btn-primary btn-lg btn-block register-button" type="submit" style="width: 105px;">Post</button>
				</div>
				<br><br><br>	
			</div>
		</div>	
	</form>

	<div id='new-post'></div>
	{% for feed in feed_data %}
	<div id="post-id-{{ feed.id }}">
		<div id="nav-container">
			<div id="navbar">
				
			{% if feed.user.account.prof_pic %}
				
					<div id="left">
						<a href="{% url 'profile:profile' feed.user.username %}">
							<img src="{{ feed.user.account.prof_pic.url }}" class="feed-prof-pic" >
						</a>
						<h4 class="post" id='feed-prof-username'>
							<a href="{% url 'profile:profile' feed.user.username %}">
								{{ feed.user.username}}
							</a>
						</h4>

					</div>
				
				{% if feed.user.username == current_user.username %}	
					<div id="right">
						<form action="{% url 'feeds:archive' feed.id %}" method="post" class="archive_post" style="float: right;margin-right: 10px;">
							{% csrf_token %}
							<button type="submit">✖</button>
						</form>
						<form class="edit" method="get" action="{% url 'feeds:edit_post' feed.id feed.images.id %}">
							<button id="edit-btn" style="float: right;margin-right: 10px;" type="submit">...</button>
						</form>
						
					</div>
				{% endif %}
				
				<br><br>
				
				{% else %}
					<div id="left">
						<a href="{% url 'profile:profile' feed.user.username %}">
							<img src="{% static 'user_profile/img/blank_picture.png' %}" class="feed-prof-pic">
						</a>
						<h4 class="post" id='feed-prof-username'>
							<a href="{% url 'profile:profile' feed.user.username %}">
								{{ feed.user.username}}
							</a>
						</h4>
					</div>
				{% if feed.user.username == current_user.username %}
					
					<div id="right">
						<form method="post" action="{% url 'feeds:archive' feed.id %}" class="archive_post" style="float: right;margin-right: 10px;">
							{% csrf_token %}
							<button type="submit">✖</button>
							
						</form>

						<form class="edit" method="get" action="{% url 'feeds:edit_post' feed.id feed.images.id %}">
							<button id="edit-btn" style="float: right;margin-right: 10px;" type="submit">...</button>
						</form>

					</div>
				{% endif %}
				
				<br><br>
				
			{% endif %}
				
				<div id="post-edit-{{feed.id }}">
					<div class="padding">
						<h4 class="caption" id="feed-caption">
							{{feed.caption}}
						</h4>
					</div>
					<div id='center'>
						<a href="{% url 'feeds:view_post' feed.id %}"><img src="{{feed.images.image.url}}" width="700px" height="500px"></a>
					</div>
				</div>
				<br><br>
				<div id="left">
					<form method="post" action="{% url 'feeds:like' feed.id %}" class="like">{% csrf_token %}
						<button id="like-btn" class="btn btn-primary btn-lg btn-block register-button" type="submit" style="float: left">Like</button>
					</form>

					
					
					<br><br>
					<h4 class="post" id="like-no{{feed.id}}" style="margin-right: 100px;">
						{{ feed.likes }} Likes
					</h4>
					<form method="get" action="{% url 'feeds:like' feed.id %}" class="likers">
						<button style="margin-right: 10px;">View who liked this...</button>
					</form>	
				</div>
				<br><br><br><br><br><br>
				<div class="comments">
				{% for comments in comment_data %}
					{% if comments.post.id == feed.id %}
						<div id="comment_id-{{ comments.id }}">
						
						{% if feed.user.username == current_user.username %}
							<form action="{% url 'feeds:delete_comment' comments.id %}" method="post" class="delete-comment">
								{% csrf_token %}
								<button style="float: right;" type="submit">x</button>
							</form>
							
							{% if comments.user.username == current_user.username %}
								<form method='get' action="{% url 'feeds:get_comment' comments.id %}" class="comment-form-active">
									{% csrf_token %}
									<button style="float: right;" type="submit">...</button>
								</form>

							{% endif %}
						{% elif comments.user.username == current_user.username %}
							<form action="{% url 'feeds:delete_comment' comments.id %}" method="post" class="delete-comment">
								{% csrf_token %}
								<button style="float: right;" type="submit">x</button>
							</form>

							<form method='get' action="{% url 'feeds:get_comment' comments.id %}" class="comment-form-active">
								{% csrf_token %}
								<button style="float: right;" type="submit">...</button>
							</form>

						{% endif %}
						
							<div class="padding-comments">
								<span class="comment-user" id="comment-user">
									<a href="{% url 'profile:profile' comments.user.username %}" style="color: black;float: left;">
										{{ comments.user.username }} |
									</a> 
								</span>
								<span class="comment">
									<p>{{ comments.comment }}</p>
								</span>
								
								<div id='comment-up-{{comments.id}}' class="edit-comment-form" style="display: none;">
									<form action="{% url 'feeds:edit_comment' comments.id %}" method="post" class="edit-comment">
										{% csrf_token %}
										{{ comment_form.comment|add_class:'text-box'|attr:"style:width:620px;"|attr:'id:comment-edit'|attr:"placeholder:Edit Comment Here" }}
										
									
									<button style="float: right;" type="submit">Edit</button>
									</form>
									<button style="float: right;" id="cancel-edit-comment-{{comments.id}}">Cancel</button>
								</div>
								
								<h4 style="font-size: 12px;">
									Commented on: {{ comments.commented_at }}
								</h4>

							</div>
						

					</div>
					{% endif %}
				{% endfor %}
				
				
				
			<div class="insertComment{{feed.id}}" ></div>
			</div>
			
		</div>

				
			
			<form method="post" action="{% url 'feeds:comment' feed.id %}" class='comment-form'>{% csrf_token %}
			{{ comment_form.comment|add_class:'text-box' }}
			<button id='create-comment' class="btn btn-primary btn-lg btn-block login-button" type="submit" style="margin-left: 570px;width: 110px;">Comment</button>
		</form>
		<br><br>
	</div>

		<div id="popup2" class="overlay2">
			<div class="popup2">
				<h2>Edit Post</h2><br>
				<button class="close2">&times;</button>
				<div class="content2">
					<form action="{% url 'feeds:edit_post' feed.id feed.images.id %}" method="post"  enctype="multipart/form-data" class="edit-post">
					{% csrf_token %}
						<div style="margin-right: 60px;">
							{{feed_form.caption }}
						</div>
						{{ picture_form.image }}

						
						<button class="btn btn-primary btn-lg btn-block register-button" type="submit" style="width: 105px;margin-left: 465px;">Edit</button>
					</form>
					<div id="info-feed"></div>
					
				</div>
				
			</div>
		</div>

	</div>
	{% endfor %}

	
{% endblock content %}